# publication settings

lang: en 

toc-title: "Contents" 
reference-section-title: "References" 
link-citations: true
metadata: false

# download settings

download: # full-text outputs
  - label: PDF
    link: LanternFinalReport.pdf
  - label: EPUB
    link: LanternFinalReport.epub
  - label: DOCX
    link: LanternFinalReport.docx
  - label: Source
    link: https://github.com/nulib-oer/lantern-report